spring :
  application :
    name : fz-chat-service
  datasource:
    url : jdbc:mysql://localhost:3306/frenzo_dev
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver
  jpa :
    hibernate :
      ddl-auto : update
    show-sql : true
  mail : 
    host : email-smtp.ap-south-1.amazonaws.com
    port : 465
    username : AKIAWADK4TT6NGYC3A5I
    password : BMu3Vu1Xa6zoOk4uDMKl6N/4OYhBfIQEgvuAmfT4ioDI
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

server :
  port : 9092

eureka :
  client:
    fetch-registry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
  instance:
    preferIpAddress : true

info:
  app:
   name: chat
   description: chat-service
   version: 0.0.1

management:
  endpoints:
     web:
       exposure:
         include: "*"
  info:
     env:
       enabled: true

token:
   access:
    expiration: 2_592_000
   refresh:
    expiration: 31_536_000
   secret:
     key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855